# Generated by Django 2.2.5 on 2020-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapimode',
            name='groupFlg',
            field=models.BooleanField(default=True, verbose_name='有效属性'),
        ),
        migrations.AlterField(
            model_name='uservarmode',
            name='varType',
            field=models.IntegerField(default=0, verbose_name='变量类型'),
        ),
    ]
