# Generated by Django 2.2.5 on 2020-06-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0002_auto_20200604_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasemode',
            old_name='createName',
            new_name='creator',
        ),
    ]
