# Generated by Django 2.2.5 on 2020-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0003_auto_20200605_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envconfigmode',
            options={'verbose_name': '执行环境配置', 'verbose_name_plural': '执行环境配置'},
        ),
        migrations.RemoveField(
            model_name='envconfigmode',
            name='releseUrl',
        ),
        migrations.AddField(
            model_name='envconfigmode',
            name='localUrl',
            field=models.URLField(default='', verbose_name='本地地址'),
        ),
        migrations.AddField(
            model_name='envconfigmode',
            name='releaseUrl',
            field=models.URLField(default='', verbose_name='预发地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envconfigmode',
            name='productUrl',
            field=models.URLField(verbose_name='正式地址'),
        ),
        migrations.AlterField(
            model_name='envconfigmode',
            name='testUrl',
            field=models.URLField(verbose_name='测试地址'),
        ),
    ]
