# Generated by Django 2.2.5 on 2020-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0004_auto_20200605_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskplanmode',
            old_name='createName',
            new_name='creator',
        ),
    ]
