# Generated by Django 2.2.5 on 2020-06-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0005_auto_20200608_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apisqllistmode',
            old_name='createName',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='taskrunlogmode',
            old_name='taskOperator',
            new_name='creator',
        ),
    ]
