# Generated by Django 2.2.5 on 2020-05-28 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConfigMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbName', models.CharField(max_length=50, verbose_name='配置名称')),
                ('dbType', models.IntegerField(choices=[(1, 'MySql'), (2, 'SqlServer'), (3, 'Oracle'), (4, 'MongoDB')], verbose_name='数据库类型')),
                ('dbServer', models.CharField(max_length=50, verbose_name='服务器ip&端口')),
                ('dbAccount', models.CharField(max_length=50, verbose_name='账号')),
                ('dbPassWord', models.CharField(max_length=50, verbose_name='密码')),
                ('dbDefault', models.CharField(max_length=50, verbose_name='默认数据库')),
                ('dbFlag', models.BooleanField(default=True, verbose_name='配置有效性')),
            ],
            options={
                'verbose_name': '数据库配置',
                'verbose_name_plural': '数据库配置',
            },
        ),
        migrations.CreateModel(
            name='ProductMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, verbose_name='产品名称')),
                ('productFlag', models.BooleanField(default=True, verbose_name='产品状态')),
                ('productTag', models.CharField(max_length=50, verbose_name='产品标识')),
                ('createName', models.CharField(max_length=50, verbose_name='创建人')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50, verbose_name='项目名称')),
                ('projectFlag', models.BooleanField(default=True, verbose_name='项目状态')),
                ('CharField', models.CharField(max_length=50, unique=True, verbose_name='项目标识')),
                ('createName', models.CharField(max_length=50, verbose_name='创建人')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('module', models.CharField(choices=[('apiTest', '接口测试'), ('webTest', 'web测试'), ('appTest', 'app测试'), ('bugManage', 'BUG管理'), ('report', '测试报告'), ('testTool', '常用测试工具')], max_length=50, verbose_name='项目所属模块')),
                ('subType', models.CharField(choices=[('testCase', '空'), ('order', '订单处理'), ('download', '下载')], default='', max_length=50, verbose_name='子类')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectMode.ProductMode')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
    ]
